name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.6

      - name: Build binary
        run: |
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          export BINARY_NAME=main-${{ matrix.goos }}-${{ matrix.goarch }}
          CGO_ENABLED=0 go build -o bin/$BINARY_NAME main.go

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: main-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/main-${{ matrix.goos }}-${{ matrix.goarch }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}